### ISSUE TITLE
Whats the difference between wild and catchable pokemons?

### ISSUE THREAD

**Issue by krzkrzkrz** [nabeelamjad/poke-api#37] opened 2016-08-10 13:16 UTC
Whats the difference between wild and catchable pokemons?

**Comment by nabeelamjad** [comment] 2016-08-10 13:49
I wouldn't really know about that, I've played the game only one or two days total. I would assume catch-able Pokemon returns a list that is in your range to click? Whereas wild could be out of range but still close enough?

**Comment by krzkrzkrz** [comment] 2016-08-10 14:04
Looking at `RECYCLE_INVENTORY_ITEM` and the other possible requests at 

https://github.com/nabeelamjad/poke-api/blob/master/lib/poke-api/pogoprotos/pogoprotos_networking_requests.rb

How is it possible to fine out which arguments are needed for those methods?

**Comment by nabeelamjad** [comment] 2016-08-10 14:06
https://github.com/nabeelamjad/poke-api/blob/master/lib/poke-api/pogoprotos/pogoprotos_networking_requests_messages.rb

If a field points to another field (such as enum), it will have a name behind it (which is another file you can open to get the number from). The README explains on how to search up.

You can also find them at https://github.com/tejado/pgoapi/wiki/recycle_inventory_item, I still intend to create a Wiki but short on time.

**Comment by krzkrzkrz** [comment] 2016-08-10 15:26
I see. Consider the following:

```
        client.catch_pokemon(
          encounter_id: pokemon[:encounter_id],
          pokeball: 1,
          normalized_reticle_size: 0.5,
          spawn_point_id: pokemon[:spawn_point_id],
          hit_pokemon: true,
          spin_modifier: 1.0,
          normalized_hit_position: 1.0
        )
```

`pokemon[:encounter_id]` and `pokemon[:spawn_point_id]` are values returned from `resp.response[:GET_MAP_OBJECTS]`.

No errors when running, this, but at the same time. Number of poke balls dont decrease and number of pokemons in inventory are the same

**Comment by nabeelamjad** [comment] 2016-08-10 15:38
I'm not sure how that API call works personally, you could have a look at this [code](https://github.com/PokemonGoF/PokemonGo-Bot/blob/63f777bac0c8cdc75d07f9ef491ca8b900c0148a/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L343), perhaps you're not in catch-able range to it?

**Comment by krzkrzkrz** [comment] 2016-08-10 15:52
```
          client.catch_pokemon(
          encounter_id: pokemon[:encounter_id],
          pokeball: 1,
          normalized_reticle_size: 1.0,
          spawn_point_id: pokemon[:spawn_point_id],
          hit_pokemon: true,
          spin_modifier: 1.0,
          normalized_hit_position: 1
        )

        ap client.call.response
```

Returns 

```
{
    :CATCH_POKEMON => {
                     :status => :CATCH_ERROR,
               :miss_percent => 0.0,
        :captured_pokemon_id => 0,
              :capture_award => nil
    },
      :status_code => 3,
          :api_url => "",
            :error => ""
}
```

**Comment by nabeelamjad** [comment] 2016-08-10 15:56
I wouldn't be able to help you with this, I've never used the API calls myself (as I don't play the game). I'm pretty sure the API works as intended, however something else is going on. Maybe someone else has a clue why?

Did you try it on **lured** or **visible** pokemon?  (Don't think it works on **wild** or **catchable** despite the name)

**Comment by krzkrzkrz** [comment] 2016-08-10 16:10
According to some guys at the Slack group pgoapi, Status code 3 indicates that something is wrong with the arguments passed. Where exactly, I am trying to figure out

**Comment by krzkrzkrz** [comment] 2016-08-10 16:24
Happen to know if I need to call `client.encounter` first?

**Comment by nabeelamjad** [comment] 2016-08-10 16:38
So if you look over at https://github.com/PokemonGoF/PokemonGo-Bot/blob/63f777bac0c8cdc75d07f9ef491ca8b900c0148a/pokemongo_bot/cell_workers/pokemon_catch_worker.py#L66

We can see the following things:
1. A `PokemonCatchWorker` class is instantiated with the `lured_pokemon` or `visible pokemon` which executes `work` (which we are looking at in the link above)
2. Fires a `create_encounter_api_call` which calls either `encounter` (if `spawn_point_id` is present for the pokemon) or else `disk_encounter`.
3. It then checks if the pokemon response does **NOT** contain `ENCOUNTER_STATUS_SUCCESS` in which case it devises a reason as to why (bags full or not in range)
4. It then does other stuff, grabs some pokemon data here and there to see if it's in the VIP or ignored pokemon list
5. It then checks some other things to calculate which ball to throw, predictability, chance, etc, etc
6. Finally it executes `catch_pokemon`, however do note that `spawn_point_id` is the `fort_id` if on condition 2 we had a `disk_encounter`

If you go over the code it should become apparent what's happening, but in any case yes, you need to create the encounter and then catch it.

**Comment by nabeelamjad** [comment] 2016-08-10 23:07
Closing this one down as well, if there's still an issue let me know but this does seem to point out to how these requests have to be called rather than anything to do with the gem itself. If you can't get it to work by Saturday then I'll help out with some sample code you can try and run.

**Closed as completed by nabeelamjad** 2016-08-10 23:07 UTC
Labels: help wanted, question
