### ISSUE TITLE
gpsoauth is not compatible with ruby 2.0.0

### ISSUE THREAD

**Issue by ipepe** [nabeelamjad/poke-api#42] opened 2016-08-21 12:34 UTC
I know that it's old as my grandma ass but that's my hosting platform and can't change it. Can we do something about it? Do I have to make a pull request in gpsoauth reverting compatibility? I don't want to use Google Login....

**Comment by nabeelamjad** [comment] 2016-08-21 13:49
Not sure why I closed this but tagging in @xssc, it does seem a lot of the things are broken for this to work (OpenSSL, hash notation, etc)

**Comment by ipepe** [comment] 2016-08-21 13:59
Well I commented out for now requiring of 'gpsoauth' and seems to be working, but I have trouble with:

```
An unknown proto fault has occured => [Unable to fetch endpoint, please try to login again.
```

**Comment by nabeelamjad** [comment] 2016-08-21 14:01
Could you enable DEBUG mode please and paste the log (with whatever sensitive information redacted), and a stack trace too.

**Comment by ipepe** [comment] 2016-08-21 14:03
I guess I don't have any sensitive information?

```
[2016-08-21T15:59:50+02:00]: DEBUG > Poke::API::Auth::PTC      --: [>] Fetching PTC ticket
[2016-08-21T15:59:51+02:00]: DEBUG > Poke::API::Auth::PTC      --: [>] Fetching PTC access token
[2016-08-21T15:59:51+02:00]: INFO  > Poke::API::Client         --: [+] Provider access token is valid for 03:00:00
[2016-08-21T15:59:51+02:00]: DEBUG > Poke::API::RequestBuilder --: [+] Creating new request
[2016-08-21T15:59:51+02:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-21T15:59:51+02:00]: INFO  > Poke::API::RequestBuilder --: [+] Using provider access token
[2016-08-21T15:59:51+02:00]: DEBUG > Poke::API::RequestBuilder --: [+] Generated RPC protobuf request 
<POGOProtos::Networking::Envelopes::RequestEnvelope: status_code: 2, request_id: 8145806132888207460, requests: [<POGOProtos::Networking::Requests::Request: request_type: :GET_HATCHED_EGGS, request_message: "">], unknown6: nil, latitude: 52.23, longitude: 21.01, altitude: 5.0, auth_info: <POGOProtos::Networking::Envelopes::RequestEnvelope::AuthInfo: provider: "ptc", token: <POGOProtos::Networking::Envelopes::RequestEnvelope::AuthInfo::JWT: contents: "TGT-48228952-ef9pnJRHWfHPdeQMw96WKRWcMEkEb1xcbcCL06KlBwFYckUiJC-sso.pokemon.com", unknown2: 59>>, auth_ticket: nil, unknown12: 989>
[2016-08-21T15:59:51+02:00]: DEBUG > Poke::API::RequestBuilder --: [+] Generated RPC protobuf encoded request 
"\b\x02\x18\xE4\x80\x80\x80\xD0\xF0\xED\x85q\"\x02\b~9=\n\xD7\xA3p\x1DJ@A\xC3\xF5(\\\x8F\x025@I\x00\x00\x00\x00\x00\x00\x14@RZ\n\x03ptc\x12S\nOTGT-48228952-ef9pnJRHWfHPdeQMw96WKRWcMEkEb1xcbcCL06KlBwFYckUiJC-sso.pokemon.com\x10;`\xDD\a"
[2016-08-21T15:59:51+02:00]: INFO  > Poke::API::RequestBuilder --: [+] Executing RPC request
[2016-08-21T15:59:52+02:00]: INFO  > Poke::API::Response       --: [+] Decoding Main RPC responses
[2016-08-21T15:59:52+02:00]: DEBUG > Poke::API::Response       --: [+] RPC response 
"\b\u0003\u0010䀀\x80\xD0\xF0\xED\x85q:[\n@\xAEjQ\xE0Խ\x81\xC6\u000E\xAD\xF9\x9F_\x98\xE8}{o+=\xF7\x8E\u038Df4\xA8\u000F\xF6\u0018\u0005<\xFF\xA5\xF4\x93\xE8\u0014\xE1L>w\x8E=\xFAB\xBF\x81\xACƦld\xE3P\x9D\xB5~\xF9T )U\u0018\u0010\x86\xF5\x87\xEC\xEA*\u001A\u0010\xD1wJ\u001C\x91\u0016\xE4\xF2<\xA0\u000E\xE3\v#c\u03A2\u0006\u0000"
[2016-08-21T15:59:52+02:00]: DEBUG > Poke::API::Response       --: [+] Decoded RPC response 
<POGOProtos::Networking::Envelopes::ResponseEnvelope: status_code: 3, request_id: 8145806132888207460, api_url: "", unknown6: [], auth_ticket: <POGOProtos::Networking::Envelopes::AuthTicket: start: "\xAEjQ\xE0\xD4\xBD\x81\xC6\x0E\xAD\xF9\x9F_\x98\xE8}{o+=\xF7\x8E\xCE\x8Df4\xA8\x0F\xF6\x18\x05<\xFF\xA5\xF4\x93\xE8\x14\xE1L>w\x8E=\xFAB\xBF\x81\xAC\xC6\xA6ld\xE3P\x9D\xB5~\xF9T )U\x18", expire_timestamp_ms: 1471789791878, end: "\xD1wJ\x1C\x91\x16\xE4\xF2<\xA0\x0E\xE3\v#c\xCE">, returns: [""], error: "">
[2016-08-21T15:59:52+02:00]: INFO  > Poke::API::Response       --: [+] Using auth ticket instead
[2016-08-21T15:59:52+02:00]: DEBUG > Poke::API::Response       --: [+] Storing auth ticket
{:start=>"\xAEjQ\xE0\xD4\xBD\x81\xC6\x0E\xAD\xF9\x9F_\x98\xE8}{o+=\xF7\x8E\xCE\x8Df4\xA8\x0F\xF6\x18\x05<\xFF\xA5\xF4\x93\xE8\x14\xE1L>w\x8E=\xFAB\xBF\x81\xAC\xC6\xA6ld\xE3P\x9D\xB5~\xF9T )U\x18", :expire_timestamp_ms=>1471789791878, :end=>"\xD1wJ\x1C\x91\x16\xE4\xF2<\xA0\x0E\xE3\v#c\xCE"}
[2016-08-21T15:59:52+02:00]: DEBUG > Poke::API::Response       --: [+] Current endpoint https://pgorelease.nianticlabs.com/plfe/rpc
[2016-08-21T15:59:52+02:00]: INFO  > Poke::API::Client         --: [+] Cleaning up RPC requests
/Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/poke-api-fd27b2c9834f/lib/poke-api/client.rb:44:in `rescue in call': An unknown proto fault has occured => [Unable to fetch endpoint, please try to login again. @ /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/poke-api-fd27b2c9834f/lib/poke-api/response.rb:58:in `store_endpoint'] (Poke::API::Errors::UnknownProtoFault)
        from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/poke-api-fd27b2c9834f/lib/poke-api/client.rb:48:in `call'
        from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/poke-api-fd27b2c9834f/lib/poke-api/client.rb:84:in `initialize_ticket'
        from /Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/poke-api-fd27b2c9834f/lib/poke-api/client.rb:30:in `login'
        from app.rb:10:in `<main>'
```

**Comment by nabeelamjad** [comment] 2016-08-21 14:15
It seems to me that Niantic is not passing you an endpoint in their response, moreover you're getting `status_code: 3` in the decoded response whereas the one I'm getting is 53 (I'm sorry, I don't know what the codes map to exactly).

I would try locally on your own machine first and with a different PTC account, I'm not entirely sure what the status code error is for (it could also be that you need to accept the terms and agreement first if it's a new PTC account).

**Comment by ipepe** [comment] 2016-08-21 14:17
It's new. The TOS is shown in Mobile App?

**Comment by nabeelamjad** [comment] 2016-08-21 14:18
Yes, there's a way to accept it as well programatically, I'll have to dig the code but it's a simple thing.

**Comment by nabeelamjad** [comment] 2016-08-21 14:24
Have a look at: https://github.com/scottstamp/pgoapi/blob/master/scripts/accept-tos.py, 

So this would translate into the following call: `@client.mark_tutorial_complete(tutorials_completed: [0], send_marketing_emails: false, send_push_notifications: false)`, though the issue is that currently the `login` method uses a separate call straight off the bat. 

If you go into the file `client.rb` and change the following method

``` ruby
def initialize_ticket
  get_hatched_eggs
  call
end
```

to 

``` ruby
def initialize_ticket
  mark_tutorial_complete(tutorials_completed: [0], send_marketing_emails: false, send_push_notifications: false)
  call
end 
```

Let me know if that works, I'm not even sure this is related to the TOS acceptance but who knows.

**Comment by nabeelamjad** [comment] 2016-08-21 16:22
The latest build now has automatic TOS acceptance, let me know if that works.

**Comment by nabeelamjad** [comment] 2016-08-21 17:56
Removed the Auto TOS accept as it might get detected too easily otherwise.

Here is how you would do it now to accept tutorials and login at the same time.

``` ruby
client = Poke::API::Client.new

client.mark_tutorial_complete(
  tutorials_completed: [0], 
  send_marketing_emails: false, 
  send_push_notifications: false
)

client.store_location('New York')
client.login('username', 'password', ptc')

```

**Comment by ipepe** [comment] 2016-08-21 18:25
```
[2016-08-21T20:25:15+02:00]: INFO  > Poke::API::Client         --: [+] Lat/Long: 52.23, 21.01
[2016-08-21T20:25:16+02:00]: DEBUG > Poke::API::Auth::PTC      --: [>] Fetching PTC ticket
[2016-08-21T20:25:16+02:00]: DEBUG > Poke::API::Auth::PTC      --: [>] Fetching PTC access token
[2016-08-21T20:25:17+02:00]: INFO  > Poke::API::Client         --: [+] Provider access token is valid for 03:00:00
[2016-08-21T20:25:17+02:00]: DEBUG > Poke::API::RequestBuilder --: [+] Creating new request
[2016-08-21T20:25:17+02:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'MARK_TUTORIAL_COMPLETE' to RPC request with arguments
[2016-08-21T20:25:17+02:00]: DEBUG > Poke::API::RequestBuilder --: [+] MARK_TUTORIAL_COMPLETE: {:tutorials_completed=>[0], :send_marketing_emails=>false, :send_push_notifications=>false}
[2016-08-21T20:25:17+02:00]: INFO  > Poke::API::RequestBuilder --: [+] Adding 'GET_HATCHED_EGGS' to RPC request
[2016-08-21T20:25:17+02:00]: INFO  > Poke::API::RequestBuilder --: [+] Using provider access token
[2016-08-21T20:25:17+02:00]: DEBUG > Poke::API::RequestBuilder --: [+] Generated RPC protobuf request 
<POGOProtos::Networking::Envelopes::RequestEnvelope: status_code: 2, request_id: 8145806132888207460, requests: [<POGOProtos::Networking::Requests::Request: request_type: :MARK_TUTORIAL_COMPLETE, request_message: "\b\x00">, <POGOProtos::Networking::Requests::Request: request_type: :GET_HATCHED_EGGS, request_message: "">], unknown6: nil, latitude: 52.23, longitude: 21.01, altitude: 9.0, auth_info: <POGOProtos::Networking::Envelopes::RequestEnvelope::AuthInfo: provider: "ptc", token: <POGOProtos::Networking::Envelopes::RequestEnvelope::AuthInfo::JWT: contents: "TGT-49109593-NLfZRLnHJ7fz1CyKXxxr5ijAZWIPPk0dKba6hchnrmf9GCHL3i-sso.pokemon.com", unknown2: 59>>, auth_ticket: nil, unknown12: 989>
[2016-08-21T20:25:17+02:00]: DEBUG > Poke::API::RequestBuilder --: [+] Generated RPC protobuf encoded request 
"\b\x02\x18\xE4\x80\x80\x80\xD0\xF0\xED\x85q\"\a\b\x96\x03\x12\x02\b\x00\"\x02\b~9=\n\xD7\xA3p\x1DJ@A\xC3\xF5(\\\x8F\x025@I\x00\x00\x00\x00\x00\x00\"@RZ\n\x03ptc\x12S\nOTGT-49109593-NLfZRLnHJ7fz1CyKXxxr5ijAZWIPPk0dKba6hchnrmf9GCHL3i-sso.pokemon.com\x10;`\xDD\a"
[2016-08-21T20:25:17+02:00]: INFO  > Poke::API::RequestBuilder --: [+] Executing RPC request
[2016-08-21T20:25:17+02:00]: INFO  > Poke::API::Response       --: [+] Decoding Main RPC responses
[2016-08-21T20:25:17+02:00]: DEBUG > Poke::API::Response       --: [+] RPC response 
"\b\u0003\u0010䀀\x80\xD0\xF0\xED\x85q:[\n@I\xBA\"\xA5M\u001F\xCF\xE90\xF3\a)R[b\xF4\x8Cey\x84\xFE\x91\xDF\u0006L'\x84*\x9Ew\xFDR\x92ɼi\xBF2x=屪8k8}\xDAUl\xAA\xF1:\xE8\xCC\xE9n8\u0011\xFA\xEA!\x83<\u0010\xF1\xFC\xD3\xF3\xEA*\u001A\u0010\r\x95\xC0\xB5\xAFB\xD9\u001DѸaȅv\xACW\xA2\u0006\u0000"
[2016-08-21T20:25:17+02:00]: DEBUG > Poke::API::Response       --: [+] Decoded RPC response 
<POGOProtos::Networking::Envelopes::ResponseEnvelope: status_code: 3, request_id: 8145806132888207460, api_url: "", unknown6: [], auth_ticket: <POGOProtos::Networking::Envelopes::AuthTicket: start: "I\xBA\"\xA5M\x1F\xCF\xE90\xF3\a)R[b\xF4\x8Cey\x84\xFE\x91\xDF\x06L'\x84*\x9Ew\xFDR\x92\xC9\xBCi\xBF2x=\xE5\xB1\xAA8k8}\xDAUl\xAA\xF1:\xE8\xCC\xE9n8\x11\xFA\xEA!\x83<", expire_timestamp_ms: 1471805718129, end: "\r\x95\xC0\xB5\xAFB\xD9\x1D\xD1\xB8a\xC8\x85v\xACW">, returns: [""], error: "">
[2016-08-21T20:25:17+02:00]: INFO  > Poke::API::Response       --: [+] Using auth ticket instead
[2016-08-21T20:25:17+02:00]: DEBUG > Poke::API::Response       --: [+] Storing auth ticket
{:start=>"I\xBA\"\xA5M\x1F\xCF\xE90\xF3\a)R[b\xF4\x8Cey\x84\xFE\x91\xDF\x06L'\x84*\x9Ew\xFDR\x92\xC9\xBCi\xBF2x=\xE5\xB1\xAA8k8}\xDAUl\xAA\xF1:\xE8\xCC\xE9n8\x11\xFA\xEA!\x83<", :expire_timestamp_ms=>1471805718129, :end=>"\r\x95\xC0\xB5\xAFB\xD9\x1D\xD1\xB8a\xC8\x85v\xACW"}
[2016-08-21T20:25:17+02:00]: DEBUG > Poke::API::Response       --: [+] Current endpoint https://pgorelease.nianticlabs.com/plfe/rpc
[2016-08-21T20:25:17+02:00]: INFO  > Poke::API::Client         --: [+] Cleaning up RPC requests
/Users/user/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/poke-api-61cf13dbd7a7/lib/poke-api/client.rb:106:in `error': Unable to fetch endpoint, please try to login again. (Poke::API::Errors::InvalidEndpoint)
```

**Comment by nabeelamjad** [comment] 2016-08-21 19:55
Interesting, you're still getting `status_code: 3`, I have no idea what this means but I'd recommend trying a different account and or machine entirely. I'm certain it's not related to the client itself.

**Comment by ipepe** [comment] 2016-08-21 20:09
I read that code 3 means ban

**Comment by nabeelamjad** [comment] 2016-08-21 22:41
Oh, well then :P

**Comment by ipepe** [comment] 2016-08-22 00:20
Where do You read those codes in output?

**Comment by nabeelamjad** [comment] 2016-08-22 05:49
Search for status, it is under decoded response.

**Closed as completed** 2016-08-24 11:43 UTC
Labels: external issue
